export const REQUEST_GET_PRODUCTS = 'REQUEST_GET_PRODUCTS';
export const REQUEST_GET_PRODUCTS_SUCCESS = 'REQUEST_GET_PRODUCTS_SUCCESS';
export const REQUEST_GET_PRODUCTS_FAILURE = 'REQUEST_GET_PRODUCTS_FAILURE';

export const GET_PRODUCTS_TO_CART = 'GET_PRODUCTS_TO_CART';
export const GET_PRODUCTS_TO_CART_SUCCESS = 'GET_PRODUCTS_TO_CART_SUCCESS';
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_TO_CART = 'REMOVE_PRODUCT_TO_CART';
export const UPDATE_AMOUNT_PRODUCT = 'UPDATE_AMOUNT_PRODUCT';
