export const REQUEST_GET_PRODUCTS = 'REQUEST_GET_PRODUCTS';
export const REQUEST_GET_PRODUCTS_SUCCESS = 'REQUEST_GET_PRODUCTS_SUCCESS';
export const REQUEST_GET_PRODUCTS_FAILURE = 'REQUEST_GET_PRODUCTS_FAILURE';
